# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'ReactiveObjC', '~> 3.0.0' 

target 'LJMVVMToolDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LJMVVMToolDemo

  target 'LJMVVMToolDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LJMVVMToolDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
